name: Checkout stubs
on: 
  push:
   branches-ignore:
     - 'stubs'
  pull_request:
   branches-ignore:
     - 'stubs'
jobs:
  checkout-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'stubs'
          path: 'stubs ./'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update stubs
          branch: ${{ github.head_ref }}