name: Checkout stubs
on:
  push:
   branches-ignore:
     - 'stubs'
  pull_request:
   branches-ignore:
     - 'stubs'
jobs:
  checkout-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Checkout stubs
        uses: Bhacaz/checkout-files@v2
        with:
          files: ./
          branch: stubs
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update stubs
