name: Checkout stubs
on:
  push:
   branches-ignore:
     - 'stubs'
  pull_request:
   branches-ignore:
     - 'stubs'
jobs:
  checkout-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Checkout stubs
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch origin
          git switch stubs
          git switch ${GITHUB_REF##*/}
          git checkout stubs ./
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update stubs
