name: Check out Stubs Branch
on:
  push:
   branches-ignore:
     - 'stubs'
  pull_request:
   branches-ignore:
     - 'stubs'
jobs:
  checkout-stubs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Stubs Branch
      uses: actions/checkout@v2
      with:
        ref: 'stubs'  # checkout 'stubs' branch
        fetch-depth: 0
    - name: Commit Stubs Changes
      run: |
        git add .
        git commit -m "Checkout Stubs Branch changes"
        git push
