# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commit_message:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Update stubs'
        # Default value if no value is explicitly provided
        default: 'Main'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Checkout stubs
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch origin
          git switch stubs
          git switch ${GITHUB_REF##*/}
          git checkout stubs ./
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.inputs.commit_message }}
